### ISSUE TITLE
Gradle Build Fails

### ISSUE THREAD

**Issue by nishp77** [lbryio/odysee-android#21]
## The Issue
- try to build the project but throws an error FileNotFoundException, more specific the 'app/twitter.properties'
### Steps to reproduce
1. Clone the repo
2. Build the Project

### Expected behaviour
Build should be successful

### Actual behaviour
Does not build the project

## System Configuration
- Device:
- Android version:

## Screenshots

![image](https://user-images.githubusercontent.com/35785259/134742190-f1f0489f-1f33-49c6-846e-18e8d2ba12b4.png)

**Comment by iamflorencejay** [comment]
> ## The Issue
> * try to build the project but throws an error FileNotFoundException, more specific the 'app/twitter.properties'
> 
> ### Steps to reproduce
> 1. Clone the repo
> 2. Build the Project
> 
> ### Expected behaviour
> Build should be successful
> 
> ### Actual behaviour
> Does not build the project
> 
> ## System Configuration
> * Device:
> * Android version:
> 
> ## Anything Else
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/35785259/134742190-f1f0489f-1f33-49c6-846e-18e8d2ba12b4.png)

You can have your own twitter.properties or change the .secret files to .properties file.

**Comment by kekkyojin** [comment]
Pull latest changes from the repository. That file is no longer needed in order to build the app.

**Comment by iamflorencejay** [comment]
> Pull latest changes from the repository. That file is no longer needed in order to build the app.

up

**Comment by nishp77** [comment]
Sorry guys I forgot about that the whole time, thanks
