### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by PeterKW** [lbryio/odysee-android#9]
Glad to see Odysee Android being worked on. At the moment I don't have Android Studio setup on my computer as I am in the middle of rebuilding it. Is there an easy way to get / compile an apk to test out?

**Comment by tzarebczan** [comment]
We will be sharing an early version later today on Reddit + Discord.

**Comment by PeterKW** [comment]
Is that OdyseeForever on reddit and the LBRY Foundation Discord? 
https://www.reddit.com/r/OdyseeForever/ 'LBRY Foundation' Discord
